### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by PinkLasagna03** [Uraneptus/MoreWoodsetFurniture#1]
Hello, I tried using this mod within my modpack on a server, sadly the server crashes due to not loading the mod correctly. Removing the mod solves the problem. Can you fix it? I love the variants of Cherry Blossom furniture!

[2024-01-27-3.log](https://github.com/Uraneptus/MoreWoodsetFurniture/files/14074270/2024-01-27-3.log)

[crash-2024-01-27_23.51.32-fml.txt](https://github.com/Uraneptus/MoreWoodsetFurniture/files/14074271/crash-2024-01-27_23.51.32-fml.txt)

**Comment by Uraneptus** [comment]
Hi, I found a possible fix for the issue and will release it soon! If that update doesn't fix the problem please open another issue here! ^^

**Comment by PinkLasagna03** [comment]
Fixed it! Thanks!
